name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Configure ${{ secrets.CLOUD_ENV }} Credentials
        uses: ${{ secrets.CONFIGURE_CREDENTIALS_ACTION}}
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          region: ${{ secrets.REGION }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
      - run: pip install -r requirements.txt
      - uses: pulumi/actions@v3.10.0
        with:
          command: preview
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
